spring.application.name=spirng-ai

server.port = 8081


# OpenAI API key

#spring.ai.openai.api-key={OPEN_AI_API}
# Ollama API key


spring.ai.ollama.base-url=http://localhost:11434
spring.ai.ollama.chat.options.model=codellama:latest



logging.level.org.springframework.ai.ollama=DEBUG